SME review
OpenLiberty/guide-grpc-intro pull request #11
Opened 2022-09-06 16:11 UTC by shin19991207

According to https://github.com/OpenLiberty/draft-guide-grpc-intro/issues/10:

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#what-is-grpc

- [x] In "For each service defined in a .proto file, gRPC uses it to generate the skeleton code for users to implement and extend. "
"it" would be better as "the definition"

- [x] "much faster" -> "faster"

- [x] "either supported languages" -> other supported languages

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#what-youll-learn

- [x] "client and server services" -> "services and their clients"    i.e. is client code a service? is 'server service' odd sounding? 

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#try-what-youll-build

- [ ] When I issue `mvn -pl system liberty:run` I see the copying of server.xml twice which looks a bit naff:

```
**[INFO] Copying 1 file to /Users/hutchig/git/draft-guide-grpc-intro/finish/system/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/hutchig/git/draft-guide-grpc-intro/finish**/system/src/main/liberty/config/server.xml.
[INFO] CWWKM2185I: The liberty-maven-plugin configuration parameter "appsDirectory" value defaults to "apps".
[INFO] CWWKM2160I: Installing application guide-grpc-intro-system.war.xml.
**[INFO] Copying 1 file to /Users/hutchig/git/draft-guide-grpc-intro/finish/system/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /Users/hutchig/git/draft-guide-grpc-intro/finish**/system/src/main/liberty/config/server.xml.
```

- [ ] `[INFO] [WARNING ] SRVE0190E: File not found: /favicon.ico` appears every time http://localhost:9080/ is hit, it also appears each time http://localhost:9081/query/properties/os.name is hit on a new browser.

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-server-streaming-call

- [ ] Should '.getPropertyName' be better called getPropertyPrefix ?

- [ ] Then, call the getPropertiesServer() -> Then, calls the getPropertiesServer()  (i.e. if you are using creates with an s at the end I think you should be consistent and used calls with an s on the end too.   Same problem with "shutdown the channel and returns"  ....mixed form of expression instructions or descriptions of what needs doing or is being done?

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-client-streaming-call

- [ ] "to implement of" -> "to implement"  
I was confused by the word 'placeholder' being used to describe what is being sent back to the client.

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-client-streaming-call

- [ ] "properties started with user." -> "properties with property names prefixed by 'user.' "

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#implementing-bidirectional-streaming-call

- [ ] "returns an instance"  and "close the server" so the same mix of description and instruction forms of words  when both bits of function have the same initial location (provided/not provided in skeleton file or RHS etc.) or perhaps I am missing something?

### https://draft-openlibertyio.mybluemix.net/guides/grpc-intro.html#running-the-tests

- [ ] It would useful to identify WHICH session one can press return in (as there are multiple session in dev mode
at this point) query.

2022-09-09 12:53 UTC, hutchig requested changes

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +The [hotspot=getProperty file=0]`getProperty` rpc defines the unary call. In this call, the client side sends a `SystemPropertyPrefix` message to the server side that returns back a `SystemPropertyVa
Why can't it send a 'name' - what if more than one property has the prefix?

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +The [hotspot=getPropertiesServer file=0]`getPropertiesServer` rpc defines the server streaming call. The client side sends a `SystemPropertyPrefix` message to the server side. The server returns back
A single value is not associated with a prefix but a single property (which has a name)

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +The [hotspot=getProperty file=0]`getProperty()` method implements the rpc unary call defined in the proto file. Use the [hotspot=pPrefix file=0]`getPropertyPrefix()` getter method that is generated b
This was correctish and is now incorrect. I thin getPropertyName would be better as getProperty here NOT anything to do with prefix. (i.e. my previous comment about Prefix did not apply to the singular property calls.)

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +The `PropertiesResource` class provides RESTful endpoints to interact with the `system` service. The [hotspot=unary file=2]`/query/properties/${propertyPrefix}` endpoint uses the unary service call t
it is not getting a property name or prix but just a property:
```
'/query/properties//${property}"
```
??

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +The [hotspot=getPropertiesServer file=0]`getPropertiesServer()` method implements server streaming rpc call. Use the [hotspot=prefix file=0]`getPropertyPrefix()` getter method to retrieve the propert
getPropertiesWithPrefix
??

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +The endpoint creates a [hotspot=createChannel2 file=1]`channel` to the `system` service and a [hotspot=createClient2 file=1]`client` by using the `SystemServiceGrpc.newStub()` API. Then, calls the [h
THe sentance "After all properties are received, shutdowns the [hotspot=closeConnection file=1]`channel` and returns the placeholder."
needs a subject like "it"  ...  it shuts down.

2022-09-09 12:53 UTC, hutchig commented on README.adoc
> +Update the `PropertiesResource` class to implement `/query/properties/user` endpoint of the query service.
the

2022-09-09 12:53 UTC, hutchig commented on finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java
> +    @Path("/{propertyPrefix}")
Unary is Name

2022-09-09 12:53 UTC, hutchig commented on finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java
> +        @PathParam("propertyPrefix") String propertyPrefix) {
Unary retains Name not prefix

2022-09-09 12:53 UTC, hutchig commented on finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java
> +        SystemPropertyPrefix request = SystemPropertyPrefix.newBuilder()
unary is name

2022-09-09 12:53 UTC, hutchig commented on finish/query/src/main/java/io/openliberty/guides/query/PropertiesResource.java
> +                                             .setPropertyPrefix(propertyPrefix).build();
unary still uses name

2022-09-09 12:53 UTC, hutchig commented on finish/system/src/main/java/io/openliberty/guides/system/SystemService.java
> +        SystemPropertyPrefix request, StreamObserver<SystemProperty> observer) {
single value retains 'name'  (only when retrieving a set prefix is used as the filter key)

2022-09-09 12:53 UTC, hutchig commented on finish/system/src/main/java/io/openliberty/guides/system/SystemService.java
>      @Override
The results are property names, it is only the filter/key which would be better as prefix. ie. only the thing that is used as a prefix

2022-09-13 18:42 UTC, hutchig approved these changes
Looks ok to me!

2022-09-13 19:13 UTC, gkwan-ibm requested changes
hi @shin19991207 

- "Creating and defining gRPC service" section
  - [x] "The `getPropertiesServer` rpc defines the server streaming call. The client side sends a `SystemPropertyName` message ..." -> "The `getPropertiesServer` rpc defines the server streaming call. The client side sends a `SystemPropertyPrefix` message ..."
  
- SystemService.proto file
  - [x] change to following
```
message SystemPropertyPrefix {
    string propertyPrefix = 1;
}
```
  - need to update the other java files that references to `getPropertyPrefix()` instead of `getPropertiesWithPrefix()`

- "Implementing server streaming call" section
  - [ ] change "... Use the `getPropertiesWithPrefix()` getter method ..." to "... Use the `getPropertyPrefix()` getter method ..."

2022-09-15 19:45 UTC, gkwan-ibm approved these changes

2022-09-15 19:45 UTC, merged