Add system service test
OpenLiberty/guide-grpc-intro pull request #54
Opened 2023-03-15 13:26 UTC by gkwan-ibm

2023-03-21 13:18 UTC, mbuamuh requested changes

2023-03-21 13:18 UTC, mbuamuh commented on README.adoc
> +include::finish/system/src/main/java/io/openliberty/guides/system/SystemService.java[]
The file name should be SystemServiceTest.java and not SystemTest.java; see: http://lg-dev1.fyre.ibm.com:4020/guides/grpc-intro.html#implementing-unit-tests-for-the-grpc-server-service
The test clss also had compilation errors

2023-03-21 15:05 UTC, mbuamuh approved these changes

2023-04-18 14:41 UTC, dmuelle requested changes
ID review, let me know if you have any questions. Thanks

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +You can test your application manually, but automated tests ensure code quality because they trigger a failure whenever a code change introduces a defect. In this section, you'll create unit tests fo
```suggestion
Although you can test your application manually, automated tests ensure consistent code quality by triggering a failure whenever a code change introduces a defect. In this section, you'll create unit tests for the gRPC server service and integration tests for the `query` service.
```

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +The required dependencies are already added to the `pom.xml` Maven configuration file for you, including JUnit5, [hotspot=grpc-testing file=0]`grpc-testing`, and [hotspot=mockito-core file=0]`mockito
```suggestion
The `pom.xml` Maven configuration file already specifies the required dependencies, including JUnit5, [hotspot=grpc-testing file=0]`grpc-testing`, and [hotspot=mockito-core file=0]`mockito-core` libraries. The `grpc-testing` dependency provides utilities for testing gRPC services and creates a mock gRPC server that simulates client-server communication during testing. The `mockito-core` dependency enables the Mockito mocking framework.
```

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +In the [hotspot=tearDown file=1]`tearDown()` static method, shutdown the `inProcessChannel` in-process channel and the `inProcessServer` in-process gRPC server.
```suggestion
In the [hotspot=tearDown file=1]`tearDown()` static method, shut down the `inProcessChannel` in-process channel and the `inProcessServer` in-process gRPC server.
```

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +The [hotspot=testGetProperty file=1]`testGetProperty()` tests the unary call to retrieve a single System property value.
```suggestion
The [hotspot=testGetProperty file=1]`testGetProperty()` tests the unary call to retrieve a single system property value.
```

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +The [hotspot=testGetServerStreamingProperties file=1]`testGetServerStreamingProperties()` tests the server streaming call to retrieve multiple System property values with a given property prefix.
```suggestion
The [hotspot=testGetServerStreamingProperties file=1]`testGetServerStreamingProperties()` tests the server streaming call to retrieve multiple system property values with a given property prefix.
```

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +The [hotspot=testGetClientStreamingProperties file=1]`testGetClientStreamingProperties()` tests the client streaming call to retrieve multiple System property values with given property names.
```suggestion
The [hotspot=testGetClientStreamingProperties file=1]`testGetClientStreamingProperties()` tests the client streaming call to retrieve multiple system property values with given property names.
```

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +*Running the tests*
using bold as a substitute for heading style creates an accessibility violation. I recommend using h3 or h4 instead, depending on how the CSS handles h4

2023-04-18 14:41 UTC, dmuelle commented on README.adoc
> +*Running the tests*
see comment at line 516

2023-04-18 16:39 UTC, gkwan-ibm commented on README.adoc
> +*Running the tests*
In guide (adoc), I double there is a h3 and h4 and also don't want to be a subsection of subsection.

2023-04-18 17:51 UTC, dmuelle commented on README.adoc
> +*Running the tests*
there's an h3 heading at line 472-  

`=== Implementing unit tests for the gRPC server service`

you might try 
`==== Running the tests`

2023-04-18 18:54 UTC, dmuelle commented on README.adoc
> +If the tests pass, you see a similar output to the following example:
```suggestion
If the tests pass, you see output similar to the following example:
```

2023-04-18 19:01 UTC, gkwan-ibm commented on README.adoc
> +*Running the tests*
addressed to use `=== Running...`

2023-04-18 19:23 UTC, dmuelle approved these changes
LGTM

2023-04-18 20:39 UTC, gkwan-ibm commented
### Review changes
- [ ]  pom.xml
  - java 11
  - jakarta is 10, microfile-profile is 6.0, and dependencies
  - LMP 3.7.1
- [ ] server.xml
  - features version
- [ ] index.html
  - license and features version
- [ ] java files
  - EPL 2.0
- [ ] License file
   - EPL 2.0

### End-to-end test
- [ ] update lgdev with `version-update-mp6` branch
- [ ] do end-to-end test and review content carefully
  - clone the `version-update-mp6` branch
  - if index.html has changes, make sure the links work

### Cloud hosted test
- [ ] generate the cloud hosted dev lab
- [ ] do end-to-end test and review content
  - clone the `version-update-mp6` branch

2023-04-25 08:28 UTC, ReeceNana commented
Ran guide end-to-end on `system-service-test` branch. 
No issues/errors when ran local or cloud-hosted.
Ready to merge. 

1. PR approval subject to Gilbert review
2. Re-test locally subject to Morgan

2023-05-11 13:19 UTC, merged