Remove grpc feature from client and update README
OpenLiberty/guide-grpc-intro pull request #61
Opened 2023-08-24 06:41 UTC by shin19991207

- Addressed https://github.com/OpenLiberty/guide-grpc-intro/issues/58
  - Removed the `grpc` feature used for server-side configurations from the `query` microservice, which represents a gRPC client, for clarity and to avoids potential confusion.
  - Updated the README to mirror the code changes, correct references based on feedback, and provide clearer descriptions.

2023-08-24 15:33 UTC, gkwan-ibm requested changes
Need to do the similar thing after the following statement for simplicity and use right endpoint. May need to confirm SME(Gordon Hutchison) exact meaning of `target`. The doc says "GRPC target endpoint". It is not clear. Is it IP or hostname or REST api endpoint?

> Configure the `grpc` element with the `target` attribute.

2023-09-05 10:44 UTC, hutchig requested changes

2023-09-05 10:44 UTC, hutchig commented on README.adoc
> +Add the [hotspot=grpc file=1]`grpc` feature to the Liberty `server.xml` configuration file. This feature enables applications running on Liberty to provide gRPC services. Configure the [hotspot=grpcC
I do not think it is helpful to say that "*" is 'accepting any endpoint.
Is is not the case that a "*" can be used to add additional config (such as adding an interceptor)
to ALL the targets.

2023-09-05 10:44 UTC, hutchig commented on README.adoc
> +Add the [hotspot=grpcClient file=3]`grpcClient` feature to the Liberty `server.xml` configuration file for the `query` service. This feature enables gRPC client support on Liberty. Configure the [hot
Personally, I think "accepting any IP address" should be something more like "applying the configuration to all remote services".

2023-09-14 14:27 UTC, hutchig requested changes
Seems a bit confusing to me to have an Inbound config value for a clinet (outbound) call?
Perhaps better left as the headersToPropogate

2023-09-14 14:27 UTC, hutchig commented on README.adoc
> +Add the [hotspot=grpcClient file=3]`grpcClient` feature to the Liberty `server.xml` configuration file for the `query` service. This feature enables gRPC client support on Liberty. Configure the [hot
"applies universally to all gRPC client calls that get made" ... client calls are not inbound?

2023-09-14 14:53 UTC, hutchig approved these changes

2023-09-15 16:08 UTC, dmuelle commented on README.adoc
> +Add the [hotspot=grpcClient file=3]`grpcClient` feature to the Liberty `server.xml` configuration file for the `query` service. This feature enables gRPC client support on Liberty. Configure the [hot
```suggestion
Add the [hotspot=grpcClient file=3]`grpcClient` feature to the Liberty `server.xml` configuration file for the `query` service. This feature enables gRPC client support on Liberty. Configure the [hotspot=grpcClientConfig file=3]`grpcClient` element with the `headersToPropagate` attribute to propagate cookies. This configuration applies universally to all gRPC client calls, as indicated by the wildcard (`*`) in the `host` attribute. If you want to learn more about `grpcClient` element configuration, see the https://openliberty.io/docs/latest/reference/config/grpcClient.html[GRPC Client Properties^].
```

2023-09-15 16:29 UTC, dmuelle approved these changes
LGTM

2023-09-15 16:39 UTC, gkwan-ibm approved these changes

2023-09-15 16:39 UTC, merged